services:
  redis: 
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - /usr/local/data:/data
    env_file: .env
    command: ["redis-server","--appendonly","yes"]
    networks:
      - app_network
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    depends_on:
      - redis
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge