services:
  redis: 
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/data:/data
    env_file: .env
    command: ["redis-server","--appendonly","yes"]